### ISSUE TITLE
Space is added on reordering

### ISSUE THREAD

**Issue by henryiii** [tox-dev/pyproject-fmt-rust#27]
When two lines are reordered, a space is sometimes added:

Before:

```toml
[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"
```

After:

```toml
[build-system]
build-backend = "hatchling.build"

requires = [
  "hatchling",
]
```
